title:  Afolabi Macaulay  
logo:  HEADSHOT.png
description:  A data Analyst with years of experience working across different sectors using statistical tools such as Advanced Excel for report Automation, SQL for data interrogation and manipulation and Power BI for Creating Business intelligence reports   .
#show_downloads: true
#google analytics:
theme: jekyll-theme-minimal
